### ISSUE TITLE
Improve notification emails

### ISSUE THREAD

**Issue by djcarter85** [paulbulman/ParkingRota#11]
In issue #2, we added highlighting for the name of the user who receives an email, so that they can see their name more quickly. The information a user wants is "Did I get a space or not?", whereas I think the information they're currently getting is "Who has got a space for tomorrow?", which is a superset of the former.

Could the email be changed to simply tell you whether you have a space or not? When I get an email I'm very rarely concerned with who else has a space.

I suspect the current way of doing it is based on the fact that the emails used to be sent out in bulk, so this feature wasn't even possible.

Perhaps if I'm interrupted it would be useful to know how many others have been interrupted (to give an estimation of how likely a space is made available).

**Comment by djcarter85** [comment]
(BTW I'm happy to submit a PR for this if it is deemed worthwhile)

**Comment by paulbulman** [comment]
I think it's worthwhile - I agree that the user is interested really in whether or not they have a space. (And you're right, the way it is at the moment is mainly a hangover from only generating a single email that was sent to all interested parties.)

I think I'd be inclined to add the "Did I get a space or not?" information without necessarily removing the "Who has got a space for tomorrow?" information - perhaps just adding [Allocated|Interrupted] to the subject would be enough, but open to other ideas. I feel like showing the full list isn't doing any harm, and it's probably simpler leaving it there than e.g. conditionally adding the number of (other) people interrupted when the recipient is interrupted themselves.

**Comment by djcarter85** [comment]
Sounds reasonable. Feel free to assign this to me and I'll raise a PR at some point.

**Comment by djcarter85** [comment]
BTW the reason I was interested is that I was trying to set up an IFTTT recipe that would notify me on my phone when the email came through, and so having that information at the beginning of the subject would be really helpful. If you can work out how to do mobile notifications then that solves my problem ... 😃
