### ISSUE TITLE
No page title for Account pages

### ISSUE THREAD

**Issue by djcarter85** [paulbulman/ParkingRota#13]
![image](https://user-images.githubusercontent.com/36643088/54524779-b5fb0a00-496a-11e9-8547-6d18e074c127.png)

**Comment by paulbulman** [comment]
Thanks for the heads up - it's a bug with ASP.NET Core (https://github.com/aspnet/Identity/issues/1737), but now you can run ASP.NET Core 2.2 in AWS (https://aws.amazon.com/blogs/developer/announcing-amazon-lambda-runtimesupport/) it may be fixable...

**Comment by paulbulman** [comment]
Ah, not quite yet, will be dependent (at least) on https://github.com/aws/aws-codebuild-docker-images/issues/161.

**Comment by paulbulman** [comment]
Should be fixed by virtue of having updated to ASP.NET Core 2.2 :)
