### ISSUE TITLE
Add "Select all next month" button on Edit Requests

### ISSUE THREAD

**Issue by djcarter85** [paulbulman/ParkingRota#15]
When a new month rolls around, a load more days are visible on the Edit Requests screen.

As someone who drives in regularly, I want to be able to request a space for the entirety of the next month.

However, I can't do this in one button click. My options are:

1. Click all the days manually.
2. Look at which days for this month I haven't requested a space, click "Select all", and then deselect days I don't want a space for this month.

Could we have a button for "Select all next month" button, which would select all days in the next month? Alternatively one button for each visible month (e.g. "Select all April").

**Comment by paulbulman** [comment]
Should be done. Sorry it was too late for this (next) month...

**Comment by djcarter85** [comment]
As it happens I filled in my requests for next month at about lunchtime today ...
