### ISSUE TITLE
Date format in emails

### ISSUE THREAD

**Issue by djcarter85** [paulbulman/ParkingRota#9]
The day-ahead allocation email has the date in dd/MM format (e.g. 19/07).

I would personally prefer ddd dd MMM format (e.g. Thu 19 Jul), because then you can see more quickly which day of the week it is.

This may extend to date formats on the website and for other allocation emails.

**Comment by djcarter85** [comment]
@paulbulman Recently someone had a space made available for the current day and it was assumed it mean the following day. I wonder whether this issue might have helped avoid that problem.

Happy to offer a PR if you'd like.

**Comment by paulbulman** [comment]
@djcarter85 yeah, happy to change it. Especially if someone else does it 🙂 

FWIW my opinion of the other usages:
* Daily summary email subject/body: change
* Request reminder email subject/body: leaning towards leave, but unimportant
* Reservation reminder email subject/body: leaning towards change, but unimportant
* Weekly summary email subject: leave
* Weekly summary email body: change
* Summary/edit requests/edit reservations UI: leave

I think the tacit heuristic at play was probably if the day is easy to infer, either from the column header in the case of the UI, or by being the start or end of a week range in the case of the emails then better to leave it; if not, in the case of the dates on their own in emails then it makes sense to change it.
